---

- name: Print hostname and OS info in debug
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  vars:
    username: myuser
    home: /home/myuser
  
  tasks:
    - name: print variables
      debug:
        msg: "Username: {{ username }}, Home dir: {{ home }}"
