---

- name: test from python 4
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  vars:
    username: myuser
    home: /home/myuser
    anotherVar: DEFAULTVALUE
  
  tasks:
    - name: print variables
      debug:
        msg: "Username: {{ username }}, Home dir: {{ home }}. anotherVar: {{ anotherVar }}"
